/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.ait.recetario.desktop;

import java.awt.MenuItem;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author aitkiar
 */
public class RecetarioDesktop extends javax.swing.JFrame implements ActionListener
{

    private Recetario recetario;
    

    /**
     * Creates new form RecetarioDesktop
     */
    public RecetarioDesktop( Recetario recetario )
    {
	this.recetario = recetario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        ShowRecipesButton = new javax.swing.JButton();
        ShowRecipesButton.setName("recipes");
        NewRecipeButton = new javax.swing.JButton();
        NewRecipeButton.setName("newRecipe");
        ExitButton = new javax.swing.JButton();
        ExitButton.setName("exit");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        ShowRecipesButton.setText("Show Recipes");
        ShowRecipesButton.addActionListener( this );
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 4, 8, 4);
        getContentPane().add(ShowRecipesButton, gridBagConstraints);

        NewRecipeButton.setText("New Recipe");
	NewRecipeButton.addActionListener( this );
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 4, 8, 4);
        getContentPane().add(NewRecipeButton, gridBagConstraints);

        ExitButton.setText("Exit");
	ExitButton.addActionListener( this );
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 4, 8, 4);
        getContentPane().add(ExitButton, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actionPerformed(java.awt.event.ActionEvent event )//GEN-FIRST:event_ShowRecipesButtonActionPerformed
    {//GEN-HEADEREND:event_ShowRecipesButtonActionPerformed
        try
        {
            switch ( ((JButton)event.getSource()).getName())
            {
                case "exit":
                    recetario.exit();
                    break;
                case "recipes":
                    Utils.browse("http://localhost:" + recetario.getPort() + "/html/index.html");
                    break;
                case "newRecipe":
                    Utils.browse("http://localhost:" + recetario.getPort() + "/html/index.html#/new");
                    break;
            }
        }
        catch ( Exception e )
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ShowRecipesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void showRecetario( final Recetario recetario)
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(RecetarioDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(RecetarioDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(RecetarioDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(RecetarioDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new RecetarioDesktop( recetario ).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton NewRecipeButton;
    private javax.swing.JButton ShowRecipesButton;
    // End of variables declaration//GEN-END:variables
}
